export const PORTFOLIO_DATA = {
  name: 'Md Faizan',
  title: 'Full-Stack Developer & Creative Technologist',
  shortBio: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quos.',
  email: 'faizan@gmail.com',
  location: 'India',
  phone : '916201855200',
  
  navigation: ['About', 'Skills', 'Experience', 'Projects', 'Education', 'Certifications', 'Contact'],

  
  socials: [
    { name: 'GitHub', url: '#', icon: 'github' },
    { name: 'LinkedIn', url: '#', icon: 'linkedin' },
    { name: 'Twitter', url: '#', icon: 'twitter' },
    { name: 'Email', url: 'mailto:faizan@gmail.com', icon: 'mail' },
  ],
  
  about: {
    heading: 'About Me',
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quos. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quos. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quos. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quos. `,
    longDescription: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quos. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quos. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quos. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quos..`,
    stats: [
      { label: 'Years Experience', value: '6+' },
      { label: 'Projects Completed', value: '50+' },
      { label: 'Happy Clients', value: '30+' },
      { label: 'Open Source Contributions', value: '100+' },
    ],
  },
  
  skills: [
    {
      category: 'Frontend',
      technologies: [
        { name: 'React', level: 'Expert' },
        { name: 'TypeScript', level: 'Expert' },
        { name: 'Next.js', level: 'Expert' },
        { name: 'Tailwind CSS', level: 'Expert' },
        { name: 'Vue.js', level: 'Intermediate' },
        { name: 'Three.js', level: 'Intermediate' },
      ],
    },
    {
      category: 'Backend',
      technologies: [
        { name: 'Node.js', level: 'Expert' },
        { name: 'PostgreSQL', level: 'Expert' },
        { name: 'GraphQL', level: 'Intermediate' },
        { name: 'REST APIs', level: 'Expert' },
        { name: 'Firebase', level: 'Intermediate' },
      ],
    },
    {
      category: 'Tools & DevOps',
      technologies: [
        { name: 'Git', level: 'Expert' },
        { name: 'Docker', level: 'Intermediate' },
        { name: 'AWS', level: 'Intermediate' },
        { name: 'CI/CD', level: 'Intermediate' },
        { name: 'Vercel', level: 'Expert' },
      ],
    },
    {
      category: 'Design',
      technologies: [
        { name: 'Figma', level: 'Intermediate' },
        { name: 'UI/UX Design', level: 'Intermediate' },
        { name: 'Accessibility', level: 'Expert' },
        { name: 'Animation', level: 'Advanced' },
      ],
    },
  ],
  
  experience: [
    {
      role: 'Senior Full-Stack Developer',
      company: 'Tech Innovations Inc.',
      period: '2022 - Present',
      duration: '2 years',
      description: 'Leading the development of scalable web applications for enterprise clients.',
      highlights: [
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quos.',
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quos.',
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quos.',
      ],
    },
    {
      role: 'Full-Stack Developer',
      company: 'Creative Digital Agency',
      period: '2020 - 2022',
      duration: '2 years',
      description: 'Built custom web solutions for startups and established brands.',
      highlights: [
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quos.',
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quos.',
        'Implemented accessible design patterns improving SEO scores',
      ],
    },
    {
      role: 'Junior Web Developer',
      company: 'StartUp Hub',
      period: '2018 - 2020',
      duration: '2 years',
      description: 'Started my career building responsive web applications.',
      highlights: [
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quos.',
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quos.',
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quos.',
      ],
    },
  ],
  
  projects: [
    {
      id: 1,
      title: 'AI Design Assistant',
      description: 'An intelligent platform that helps designers create mockups and prototypes using AI.',
      tags: ['React', 'Next.js', 'OpenAI', 'Tailwind', 'TypeScript'],
      image: '/projects/ai-assistant.jpg',
      link: '#',
      githubUrl: '#',
      liveUrl: '#',
      featured: true,
    },
    {
      id: 2,
      title: 'Real-time Analytics Dashboard',
      description: 'Interactive dashboard for monitoring application performance and user metrics in real-time.',
      tags: ['React', 'WebSocket', 'PostgreSQL', 'D3.js', 'Node.js'],
      image: '/projects/analytics.jpg',
      link: '#',
      githubUrl: '#',
      liveUrl: '#',
      featured: true,
    },
    {
      id: 3,
      title: 'E-commerce Platform',
      description: 'Full-featured e-commerce solution with inventory management and payment processing.',
      tags: ['Next.js', 'Stripe', 'MongoDB', 'TypeScript', 'Redux'],
      image: '/projects/ecommerce.jpg',
      link: '#',
      githubUrl: '#',
      liveUrl: '#',
      featured: true,
    },
    {
      id: 4,
      title: 'Social Collaboration App',
      description: 'Team collaboration platform with real-time messaging and file sharing capabilities.',
      tags: ['React', 'Firebase', 'Tailwind', 'WebRTC'],
      image: '/projects/collaboration.jpg',
      link: '#',
      githubUrl: '#',
      liveUrl: '#',
      featured: false,
    },
    {
      id: 5,
      title: 'Educational Learning Platform',
      description: 'Interactive online learning platform with video lessons, quizzes, and progress tracking.',
      tags: ['Next.js', 'PostgreSQL', 'GraphQL', 'Video.js'],
      image: '/projects/learning.jpg',
      link: '#',
      githubUrl: '#',
      liveUrl: '#',
      featured: false,
    },
    {
      id: 6,
      title: 'Open Source CLI Tool',
      description: 'Developer-friendly CLI tool for scaffolding modern web projects with best practices.',
      tags: ['TypeScript', 'Node.js', 'Commander.js', 'Open Source'],
      image: '/projects/cli.jpg',
      link: '#',
      githubUrl: '#',
      liveUrl: '#',
      featured: false,
    },
  ],
  
  education: [
    {
      degree: 'Bachelor of Science',
      field: 'Computer Science',
      institution: 'University of Technology',
      period: '2015 - 2019',
      grade: '3.8 / 4.0',
      description: 'Specialized in Software Engineering and Web Technologies',
      coursework: ['Data Structures', 'Algorithms', 'Web Development', 'Database Design', 'Mobile Development'],
      highlights: ['Dean\'s List 2018-2019', 'Scholarship recipient', 'Class of 2019'],
    },
    {
      degree: 'Diploma',
      field: 'Advanced Programming',
      institution: 'Tech Academy',
      period: '2014 - 2015',
      grade: 'Distinction',
      description: 'Intensive full-stack development bootcamp',
      coursework: ['JavaScript', 'React', 'Node.js', 'MongoDB', 'Project Management'],
      highlights: ['Top 5% of cohort', 'Completed capstone project'],
    },
  ],
  
  certifications: [
    {
      id: 1,
      title: 'AWS Certified Solutions Architect',
      issuer: 'Amazon Web Services',
      issueDate: 'June 2023',
      expiryDate: 'June 2025',
      credentialId: 'AWS-SA-2023-001',
      credentialUrl: '#',
      category: 'Cloud',
      icon: 'cloud',
    },
    {
      id: 2,
      title: 'Google Cloud Professional Developer',
      issuer: 'Google Cloud',
      issueDate: 'March 2023',
      expiryDate: 'March 2025',
      credentialId: 'GCP-DEV-2023-001',
      credentialUrl: '#',
      category: 'Cloud',
      icon: 'cloud',
    },
    {
      id: 3,
      title: 'React Advanced Patterns',
      issuer: 'Frontend Masters',
      issueDate: 'January 2023',
      expiryDate: '',
      credentialId: 'FM-REACT-2023-001',
      credentialUrl: '#',
      category: 'Frontend',
      icon: 'code',
    },
    {
      id: 4,
      title: 'TypeScript Professional',
      issuer: 'TypeScript Academy',
      issueDate: 'November 2022',
      expiryDate: '',
      credentialId: 'TS-PROF-2022-001',
      credentialUrl: '#',
      category: 'Frontend',
      icon: 'code',
    },
    {
      id: 5,
      title: 'Full-Stack Web Development',
      issuer: 'LinkedIn Learning',
      issueDate: 'August 2022',
      expiryDate: '',
      credentialId: 'LL-FULLSTACK-2022-001',
      credentialUrl: '#',
      category: 'Full-Stack',
      icon: 'layers',
    },
    {
      id: 6,
      title: 'Web Accessibility Specialist',
      issuer: 'International Association of Accessibility Professionals',
      issueDate: 'May 2022',
      expiryDate: 'May 2025',
      credentialId: 'IAAP-WCAG-2022-001',
      credentialUrl: '#',
      category: 'Accessibility',
      icon: 'accessibility',
    },
  ],

  footer: {
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quos.',
    availability: 'Available for new projects',
  },
};
